### ISSUE TITLE
Set padding-top to > 0 for site-header

### ISSUE THREAD

**Issue by delucis** [HGNM/hgnm-2014#2]
_From @jsbean on January 3, 2016 21:58_

Is there an aesthetic argument for having no padding between the top of the page and the `site-header`?

My intuition would be to insert some space there to converse properly with the other instances of whitespace.

I propose shoving just a little bit in there.

_Copied from original issue: HGNM/hgnm-2014#1_

**Comment by delucis** [comment]
@jsbean: It’s funny that @josiah-wolf-oberholtzer argued for this exact thing when the site first launched. I like the way the serifs of the H, N & M connect with the top of the window. It does also has the added bonus of saving a little screen real estate. Open to persuasion though!

The negative margin on viewports < 45em is set here: https://github.com/HGNM/hgnm-2014/blob/master/scss/style.scss#L1314

**Comment by josiah-wolf-oberholtzer** [comment]
I have to agree with @jsbean: the lack of padding has always struck me as odd. I instinctively attempt to page up when I look at the site because this sort of typographic clipping is pretty atypical.

**Comment by delucis** [comment]
What is this? A democracy? OK, I give in.

@josiah-wolf-oberholtzer in the meantime you can enjoy this: 235d5f66ea23c583a7a90e2c58e2609741e43503

**Comment by jsbean** [comment]
These arguments aren't needed, but I just came to this and hadn't submitted it yet:

I can see the attraction of the flush serifs, however, the sawed-off tittle of the `i` and the flag terminal of the `f` keep me pulling down at the whole page thinking that I am missing something.

Considering the design of this is scroll-based, I would argue that saving screen real estate is a non-goal.

**Comment by jsbean** [comment]
I could imagine tucking-in the bits with the red arrows., and make general considerations of margins containers, titles, and contents.

[hgnm_website.pdf](https://github.com/HGNM/hgnm-2014/files/76810/hgnm_website.pdf)

**Comment by josiah-wolf-oberholtzer** [comment]
@jsbean: now that you've annotated the spacing, there sure are a wide variety of margins / gutters in play here.

**Comment by jsbean** [comment]
@josiah-wolf-oberholtzer: yeah, I think simplifying these relationships would clean up the flow.

**Comment by delucis** [comment]
Yikes. I guess my in-browser prototyping made me sloppy. Once we figure out a solid build process, we can open this up to some serious SASS clean-up.

**Comment by jsbean** [comment]
:+1: Looking forward to helping out once I've got a moment!

**Comment by delucis** [comment]
Set `padding-top` to `1.5em`. Feel free to create a new issue for addressing general whitespace balance.
