### ISSUE TITLE
Building of site

### ISSUE THREAD

**Issue by delucis** [HGNM/hgnm-2014#3]
_From @jsbean on January 3, 2016 22:2_

What would be the best way for me to make a change, and make a pull request for this repo, if I were to be so inclined?

Remind me: Is the building of the site all through WordPress? What would be a valid workflow to verify changes made on my end?

_Copied from original issue: HGNM/hgnm-2014#2_

**Comment by delucis** [comment]
Just realising this is not actually as simple as I would make it if I were starting afresh. What are you hoping to investigate?

I’ll try to write some instructions, but briefly: clone this repo to the `themes` directory of a local WordPress install ([using MAMP to run Apache & MySQL locally](https://codex.wordpress.org/Installing_WordPress_Locally_on_Your_Mac_With_MAMP), for example). However, you need [Advanced Custom Fields Pro](http://www.advancedcustomfields.com/pro/) as well as this [Date/Time plugin](https://github.com/soderlind/acf-field-date-time-picker) activated before activating the theme, and the former requires HGNM’s license key, which obviously I can’t post here.

Finally, while the PHP is all written by hand, the CSS is written as SCSS and then compiled. However, this is before I learned anything about [Grunt](http://gruntjs.com/) and equivalents, so I was compiling the SCSS with [Scout](https://mhs.github.io/scout-app/). :-1: 

Definitely some improvements possible here — I’ll start with proper instructions in the README soon!

**Comment by jsbean** [comment]
Ok, no worries! I was just thinking of fooling with the styling (e.g., #2 ) to propose minor changes. 

More than anything, I wanted to get my feet wet in the thing for experience. At some point, maybe I can get you a coffee and you can walk me through some of the details if I don't figure 'em out, and you can hand me top-secret info.

**Comment by delucis** [comment]
Cool — I’d fool around with Chrome Dev Tools/Firebug/in-browser inspection tool of your choice for #2.

:+1: for the rest!

**Comment by delucis** [comment]
Oh, and the heading typeface [Dala Floda](https://commercialtype.com/catalog/dala_floda), is also not bundled with the repo for licensing reasons. Proprietary software is a pain in the ass!

**Comment by josiah-wolf-oberholtzer** [comment]
Definitely use node, npm and Grunt for building the site's static assets.

For installing, I would create a Makefile to `git clone` or `curl` the appropriate repos into a directory. License keys can go into a text file to be `cat`'d at the correct steps during install. Put the license file's name into a `.gitignore` so it won't be versioned.

Export some dummy data for import into WP, etc.

The entire install process should just take a single `make install`.

**Comment by delucis** [comment]
Agreed. Although I won’t get to this soon (my computer is currently at the repair shop after most helpfully packing up on the eve of the JACK deadline), I’m reopening this as it’s a very good idea.

Any ideas for actual licensed content? The font files are one thing, but I’m realising that while the license key is needed to turn on updates on the Advanced Custom Fields plugin, the plugin itself is also not available freely. Is it possible to manage that with a Makefile?

**Comment by josiah-wolf-oberholtzer** [comment]
Can you be more specific about how you're getting these non-free plugins? Does "not available freely" mean you were emailed the plugin or some such?

**Comment by delucis** [comment]
For both plugin & fonts: e-mailed a download link — those links could be incorporated into some kind of private file? (This would be easier if this wasn’t a free Organisation and we could just make the repo private.)

**Comment by josiah-wolf-oberholtzer** [comment]
See https://gist.github.com/josiah-wolf-oberholtzer/dddff9619dd991a2ce95

```
$ make private-plugin-one
. ./private-keys.conf && \
	echo "Installing plugin one with private key \"$PLUGIN_ONE_KEY\""
Installing plugin one with private key "foo"
```

The Makefile sources the variables in the private configuration file, allowing subsequent commands to use them as substitutions. Keep the Makefile under version control and distribute the private configuration file with the plugin keys to anyone else building the project. Obviously put the name of the configuration file into your project `.gitignore` so no-one accidentally commits it.

**Comment by delucis** [comment]
Amazingly, I’m actually slowly getting this to work.

Would one of you mind testing the steps outlined here: https://github.com/HGNM/hgnm-wp-dev

This takes care of a consistent development environment, running WordPress inside a VM, it also populates the clean WordPress install with required plugins, the `hgnm-2014` theme, and data from the real life <http://hgnm.org>.

The next step will be a simple build wrapper (probably Grunt) for the theme to handle SCSS —> CSS processing.

**Comment by josiah-wolf-oberholtzer** [comment]
Yes, use Grunt. That's simple enough.

**Comment by delucis** [comment]
See [README](https://github.com/HGNM/hgnm-2014#hgnm-2014) for a new quick and simple development guide.

The “build process” is so simple we don’t even need Grunt, just `node-sass` called from a couple of `npm` scripts.

`npm start` in the theme directory builds `scss/style.scss` to `style.css`, and watches for changes.

If one of you can confirm this is all working for you, then we can close this! 🎉

**Comment by jsbean** [comment]
Sleep first.

**Comment by jsbean** [comment]
All goes well until running `./bootstrap.sh`:

```
Installing hgnm-2014 WordPress theme...
Cloning into 'wordpress/wp-content/themes/hgnm-2014'...
Warning: Permanently added the RSA host key for IP address '###.##.###.###' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Can’t find directory: wordpress/wp-content/themes/hgnm-2014. Fatal error…
```

Did I miss somewhere where I was supposed to submit credentials?

**Comment by delucis** [comment]
Weird. `./bootstrap.sh` is failing when it [tries to clone the `hgnm-2014` repo](https://github.com/HGNM/hgnm-wp-dev/blob/master/bootstrap.sh#L48), which I didn’t think you needed credentials for (it’s public). Because the script clones over SSH, it *might* be trying to authenticate you via SSH, in which case you may need to [set up your SSH keys](https://help.github.com/articles/generating-an-ssh-key/).

Although you did manage to `git clone` the `hgnm-wp-dev` repo without any trouble, so that’s double weird.

**Questions**

1. Did you do these two steps in different places/over different networks?

    ([Documentation](https://help.github.com/articles/which-remote-url-should-i-use/#cloning-with-https-urls-recommended) suggests maybe SSH cloning won’t work “behind a firewall or proxy.”)

2. Do you have SSH keys set up/do you use SSH for other repos?

3. I’ve changed your repo permissions from ‘Write’ to ‘Admin.’ Shouldn’t affect anything, but try again just in case.

4. If 3 still failing and answered “1: no; 2: yes”, try replacing [line 48 in `bootstrap.sh`](https://github.com/HGNM/hgnm-wp-dev/blob/master/bootstrap.sh#L48) with the following:

    ```sh
git clone https://github.com/HGNM/hgnm-2014.git wordpress/wp-content/themes/hgnm-2014
    ```
5. Any luck?

**Comment by delucis** [comment]
Googling your error message, suggests SSH keys may in fact be the culprit: http://stackoverflow.com/questions/12940626/github-error-message-permission-denied-publickey

I chose SSH over HTTPS here as it makes pushing changes to the repos later easier.

**Comment by jsbean** [comment]
Strange, I am relatively certain it is set-up for github as it is used continuously. But lemme check.

**Comment by jsbean** [comment]
1.  I did do this within two different networks. I will try from scratch all here just to see.
2. Re: SSH keys: `github_rsa github_rsa.pub` should be adequate?
3. I tried again (from half-way through), and it failed. I will try from the top.

**Comment by jsbean** [comment]
Ahh, now here is a thing:

When I first tried cloning `git clone git@github.com:HGNM/hgnm-2014.git` in the first step, I get: 
```Bash
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Then I changed it to `git clone https://github.com/HGNM/hgnm-2014`, which works just fine.

Considering that, I will try changing line 48 in `./bootstrap.sh`.

One moment ...

**Comment by delucis** [comment]
Ok! So I’m going to hazard a guess that it’s a local network issue with SSH. If you had success first and not later, and HTTPS works, then that seems pretty convincing.

**Comment by jsbean** [comment]
All things are good to go!

**Comment by jsbean** [comment]
I did change line 48 in `./boostrap.sh`, which did it.

**Comment by jsbean** [comment]
Thanks for hangin' in there with me!

I might mention the `npm` dependency in the `hgnm-wp-dev`. Seems obvious, but worth putting up there.

**Comment by delucis** [comment]
**Hold up.** I *also* can’t clone (or push) over SSH today. There is something bigger going on that I’m not sure of. Let me investigate.

**Comment by delucis** [comment]
@jsbean The problem seems to have resolved itself on my end. Maybe GitHub’s servers were experiencing some trouble? In any case, I think I can close this. I’ve added [an optional `--https` flag to `bootstrap.sh`](https://github.com/HGNM/hgnm-wp-dev#3-configure-wordpress-installation) that allows cloning over HTTPS if the user wants to.

I’m going to keep the `npm` dependency mention in the `hgnm-2014` README, as it’s strictly speaking a development dependency for the theme, rather than for the development environment.

**Comment by jsbean** [comment]
Ahh, of course.
