### ISSUE TITLE
Advanced Custom Fields link broken

### ISSUE THREAD

**Issue by jsbean** [HGNM/hgnm-2014#6]
As of 2016-06-04 1:09am UTC + 2, the link for [advanced custom fields 5 beta](https://github.com/AdvancedCustomFields/acf5-beta) is broken.

Though the bug is not yours, it is broken at the [source](https://www.advancedcustomfields.com/blog/acf5-public-beta-now-open/).

**Comment by delucis** [comment]
Oh right — once it moved out of beta into commercial plugin world the repo evaporated of course. I’ll amend.
